sudo: required
dist: trusty

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - npm install -g grunt-cli

install:
  - bundle install
  - npm install grunt grunt-html --save-dev
  - pip install --user awscli


# environment
language: ruby
rvm:
  - 2.4.2
jdk:
  - oraclejdk8

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

before_deploy: if [[ ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} != master ]]; then
  bundle exec jekyll clean && bundle exec jekyll build --baseurl /root/${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} && $TRAVIS_BUILD_DIR/scripts/updatePullRequest.sh;
  else
  bundle exec jekyll clean && bundle exec jekyll build;
  fi

deploy:
  - provider: s3
    access_key_id:
      secure: YyiqDNPNeo2TmphuofP3CeZfbiPnBKUu6G33s8/mRo9+yqnGQrORvT2Y/5nYBZGmDcraorYAy2Bm+xfP6eTR3KhC4EVpp1LgvpUeiFiZ7d5Gd+RNb8LDMOwqHaxkVuEB7B6zSBPJsqJPGWr/2LVG/mt+fP6K6pDF3jmr86zGsIdjK+Ki6DCjW1ot+IWlRh95ap681f8cRCL7FZKjB6ejtg7BlHM0VcdyxYiW16QGcadfSwuovCLlde+wOFYrYQ4sJCQGZcBtIwp8MfffTs2HBcQ8msujEnQ/UTTYY2sjLiRqqWh2hQBtQGjN0yczPZvDdC9VZDhT6vfP3NSfpQC8qqNhemSpN8zENP+7UvAOMZA+WEvdqOgsAa6nniRS8zKwUvOKcI3nU/yjfSGpitI6WEUaWdcw5e8JSJ6HllvXST6GRQRZKs32nSflhv+TAGMpIIKQ/TwFMDx8OiB6Tb6OuXNY/7NS6phB4zBC+Cg+XoiLigbrcTHxrwQKCYGfwbrRpIT95E/KfHWHwwG6Ci7U/1LVF2eN/Cb+FxGL/x5xEbRiu8nT6z1tDG55zws32CXmT0pxYpk/PAgNVXn1QsnfQ4Y5gE6IKcDt3HwGfu65MSWwl+5jYc53N9hQgwVE5Iq6f2mWojZW+mbBi1yc6UGAtGex5YHMUqiuhsUW3x8yhOI=
    secret_access_key:
      secure: WNKiHNSikR74DxG53klLdhqMVk38kE4delhRWHrrpmDLqjrM8iwp9PBVP8KnhuMqFjTMgLJeTFdGTLNIFU6/7pjfj8Kzce44nVxE8htIVFo/LKmAFPbIUWI/X3wzPanfA1GhTGS7TbTH0CnsQ4B2xRpu0PTy/UmK/8/96ifLezu5np/4iFEXCDUpMkZ/1IFQqzcPyZKZ/Zb3WzPP4dinZiQ6FwAJCy7V6IoLiNUpFk9E3fo5xzM8dTSaBDtTQidSUxJSabS3qGtLGN8aD+bY5i5+kHwCn4yrFi4+PEgJvlOUzOMdHFa2OcnftuBdAfPuJbRo1gC+d5wvwlp3NKvTb2RmbpeyUuJbpfLF4y2eJ7GXmpt2wC5Nxd94fT5m8lGL5k2v2nif2vfe7Rn2JHH0Ovt5EyyhWyDiTVH6nkOsVY/EL7OdhbkqYq8wsQC3MisWpi89/KR2A66W0+PTWf6szlKIu1lhBxF1vIjyQBUWvr9iqMnaVKctyEaQiu3Zz2gEZHEgRyUfpX274z29sUkgfu+I219M7RQ/++qm9m5xZ2+/Ff852E+Dhv7NKz2bc0FsN/XPrU1BNOs4Y+zbmLzpd7TDdl1tdqQUpV3ZyTC1hQLvdR+e2Ev+pYswxzgGfIDroGGWJBHXPoGCxKJiZnxX6K2PeG/1QXLjhj3mNEJe2xE=
    bucket: iiif-root-website
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    local_dir: _site
    on:
      branch: master
  - provider: s3
    access_key_id:
      secure: XS8k7NLXkJrnZU3BA8tlo/X4j2QaBsw61cD0lWhOwU+6QhKW30pCDqg1E7haGQXuPI86VMd+vE5Ru5DPyISN5bZwZ2JwUPkgyfeMzZI6ydlWJI+b7674izp77pYnTPsjKIGhvNhYOzAAlTr01L+R6zux0scRsMxem4bZKg5r3eEOG10Tg3BoH7elxNPdK+5009nCBOpHzlA8jOrauX343oQcoGcaLn91C3bqk69m9zMCMZboFq7bgYGmDSjpOTxIpaYzF8C51qYO6DR0DmWCuMpIs28wkGUrrbut++AXjEg8aSLzU4op0Uxkf2d7yPEsr7OA3o0Yxqx9JQ779TwufQv5jGlcg8MdYh8MMcYqKWvxKX/DYiH5UziqMkKstxuOnkZ4fWTS1je8LurnhuGr+2gEaFOUhlgJWgOeR4GZkgehbHUZCyz9lH2rI1rhse0vu1/L+bNxFZEa0EnXTKukbQJYUBuJBF6sX+ZHYajqlf5D37jhRf/4d9IdbdRJwEAG6Lq7rIa6SptbC67DPG1svw3M/7qLB/jfapC0oduGzgdYA2sGqWyvbUohBdF1Q1xg6KaQJ7GHLAJcLHL1VRDnTxiVas9kdyvSPLf8iORsH5OCe1WzYTaXD15gjq2pVm66Id9w+cHRyHcl2N583XauAyGwVih8mGVCRnSrNIHnxHc=
    secret_access_key:
      secure: atdxXamljGvfmuGuEWPQIIf93K8ScoihwxjxCxjISsZ182sF/8tzHLZiHB4wTY9B2sj0S3umQs6udwqGT1RnddmWrzY1BI8eM0xaavoCaayUpvmbLctYUIr8mn4NqGJ5jw9EqyJJ3l688MaRM9xSumHXbDjO6wkFPKc6DR/vRiLwXGV+54tHVNcMFayd4VHmYJIsqkjMYznd86Bv7UXoBG92rCJP8fXhEieilbUtpTGB9XnwjRTUYUElozIlMI8VLv4Iow8r+BGqbKs13kMkT1UpC0LxIzu5rxfC/79efkQbqpE/hNvXe3Dt1EN7uQfSao2XBdgrL0U19ckRd5wq2EBn+XHwZ2MSNMzrXWFUKkv5GdXfKkLzptk+wnAetJZrwycxK1exo1mnexAbwUn0nkeZyt8rVtjob2OgnfccURwXbGc3x1V2qYfUWkSCy+K/7zfpnAem/XWz3yuXSmqR+i8dq2UFqxB+cXj+76JhEatqzLvCmaU9cIEqXJgr1hCdxpwvkc8VvcJDnDiYaK1ZmS6KrNR6tU5txG7oDGtEDokffcqds3Zr0R1/Mw7EEIGSDZ9dTj0aiRLQjYqiJ8yF1+Ta0dGEjBOjuIkyqfS81Ihkz/fAHNVvSHkoA9lOYPfT8r7Sd/6qX9cBRfoZ0e6V1IYYODjyocY2Wy65rvXBo0w=
    bucket: preview.iiif.io
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    local_dir: _site
    upload-dir: "root/$TRAVIS_BRANCH"
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH != master"
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_LIVE --paths "/*"
  - test $TRAVIS_BRANCH != "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_PREVIEW --paths "/root/$TRAVIS_BRANCH/*"


notifications:
  email:
    recipients:
      - "glen.robson@gmail.com"
    on_success: "change"
    on_failure: "change"
